// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: single_jieba.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CutReq) Reset() {
	*x = CutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_single_jieba_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutReq) ProtoMessage() {}

func (x *CutReq) ProtoReflect() protoreflect.Message {
	mi := &file_single_jieba_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutReq.ProtoReflect.Descriptor instead.
func (*CutReq) Descriptor() ([]byte, []int) {
	return file_single_jieba_proto_rawDescGZIP(), []int{0}
}

func (x *CutReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word []string `protobuf:"bytes,1,rep,name=word,proto3" json:"word,omitempty"`
}

func (x *CutResp) Reset() {
	*x = CutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_single_jieba_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutResp) ProtoMessage() {}

func (x *CutResp) ProtoReflect() protoreflect.Message {
	mi := &file_single_jieba_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutResp.ProtoReflect.Descriptor instead.
func (*CutResp) Descriptor() ([]byte, []int) {
	return file_single_jieba_proto_rawDescGZIP(), []int{1}
}

func (x *CutResp) GetWord() []string {
	if x != nil {
		return x.Word
	}
	return nil
}

var File_single_jieba_proto protoreflect.FileDescriptor

var file_single_jieba_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x6a, 0x69, 0x65, 0x62, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x6a, 0x69, 0x65,
	0x62, 0x61, 0x22, 0x22, 0x0a, 0x06, 0x43, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x43, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x41, 0x0a, 0x0b, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4a,
	0x69, 0x65, 0x62, 0x61, 0x12, 0x32, 0x0a, 0x03, 0x43, 0x75, 0x74, 0x12, 0x14, 0x2e, 0x73, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x6a, 0x69, 0x65, 0x62, 0x61, 0x2e, 0x43, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x6a, 0x69, 0x65, 0x62, 0x61,
	0x2e, 0x43, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x73, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x6a, 0x69, 0x65, 0x62, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_single_jieba_proto_rawDescOnce sync.Once
	file_single_jieba_proto_rawDescData = file_single_jieba_proto_rawDesc
)

func file_single_jieba_proto_rawDescGZIP() []byte {
	file_single_jieba_proto_rawDescOnce.Do(func() {
		file_single_jieba_proto_rawDescData = protoimpl.X.CompressGZIP(file_single_jieba_proto_rawDescData)
	})
	return file_single_jieba_proto_rawDescData
}

var file_single_jieba_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_single_jieba_proto_goTypes = []interface{}{
	(*CutReq)(nil),  // 0: single_jieba.CutReq
	(*CutResp)(nil), // 1: single_jieba.CutResp
}
var file_single_jieba_proto_depIdxs = []int32{
	0, // 0: single_jieba.SingleJieba.Cut:input_type -> single_jieba.CutReq
	1, // 1: single_jieba.SingleJieba.Cut:output_type -> single_jieba.CutResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_single_jieba_proto_init() }
func file_single_jieba_proto_init() {
	if File_single_jieba_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_single_jieba_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_single_jieba_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_single_jieba_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_single_jieba_proto_goTypes,
		DependencyIndexes: file_single_jieba_proto_depIdxs,
		MessageInfos:      file_single_jieba_proto_msgTypes,
	}.Build()
	File_single_jieba_proto = out.File
	file_single_jieba_proto_rawDesc = nil
	file_single_jieba_proto_goTypes = nil
	file_single_jieba_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SingleJiebaClient is the client API for SingleJieba service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SingleJiebaClient interface {
	Cut(ctx context.Context, in *CutReq, opts ...grpc.CallOption) (*CutResp, error)
}

type singleJiebaClient struct {
	cc grpc.ClientConnInterface
}

func NewSingleJiebaClient(cc grpc.ClientConnInterface) SingleJiebaClient {
	return &singleJiebaClient{cc}
}

func (c *singleJiebaClient) Cut(ctx context.Context, in *CutReq, opts ...grpc.CallOption) (*CutResp, error) {
	out := new(CutResp)
	err := c.cc.Invoke(ctx, "/single_jieba.SingleJieba/Cut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SingleJiebaServer is the server API for SingleJieba service.
type SingleJiebaServer interface {
	Cut(context.Context, *CutReq) (*CutResp, error)
}

// UnimplementedSingleJiebaServer can be embedded to have forward compatible implementations.
type UnimplementedSingleJiebaServer struct {
}

func (*UnimplementedSingleJiebaServer) Cut(context.Context, *CutReq) (*CutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cut not implemented")
}

func RegisterSingleJiebaServer(s *grpc.Server, srv SingleJiebaServer) {
	s.RegisterService(&_SingleJieba_serviceDesc, srv)
}

func _SingleJieba_Cut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SingleJiebaServer).Cut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/single_jieba.SingleJieba/Cut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SingleJiebaServer).Cut(ctx, req.(*CutReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SingleJieba_serviceDesc = grpc.ServiceDesc{
	ServiceName: "single_jieba.SingleJieba",
	HandlerType: (*SingleJiebaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cut",
			Handler:    _SingleJieba_Cut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "single_jieba.proto",
}
